### ISSUE TITLE
Drop creation date from RAMF messages

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relayverse#30]
Having the creation date is causing more trouble than it solves (e.g., https://github.com/relaycorp/relaynet-gateway-android/issues/251, https://github.com/relaycorp/awala-endpoint-android/issues/34).

So we should just have the expiry date (replacing the TTL since there wouldn't be any time reference any more).

# TODO

- [ ] Update the specs.
- [ ] Implement changes in Node.js library.
- [ ] Integrate changes in Node.js apps and other libraries.
- [ ] Implement changes in JVM library.
- [ ] Integrate changes in JVM/Android apps and other libraries.

**Comment by gnarea** [comment]
Dropping this for the reason explained in https://github.com/AwalaNetwork/specs/issues/82#issuecomment-1217200092
